// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	events "github.com/walkline/ToCloud9/shared/events"
)

// FriendsServiceProducer is an autogenerated mock type for the FriendsServiceProducer type
type FriendsServiceProducer struct {
	mock.Mock
}

// FriendAdded provides a mock function with given fields: payload
func (_m *FriendsServiceProducer) FriendAdded(payload *events.FriendEventAddedPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.FriendEventAddedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendRemoved provides a mock function with given fields: payload
func (_m *FriendsServiceProducer) FriendRemoved(payload *events.FriendEventRemovedPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.FriendEventRemovedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NoteUpdated provides a mock function with given fields: payload
func (_m *FriendsServiceProducer) NoteUpdated(payload *events.FriendEventNoteUpdatePayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.FriendEventNoteUpdatePayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatusChange provides a mock function with given fields: payload
func (_m *FriendsServiceProducer) StatusChange(payload *events.FriendEventStatusChangePayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.FriendEventStatusChangePayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFriendsServiceProducer interface {
	mock.TestingT
	Cleanup(func())
}

// NewFriendsServiceProducer creates a new instance of FriendsServiceProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFriendsServiceProducer(t mockConstructorTestingTNewFriendsServiceProducer) *FriendsServiceProducer {
	mock := &FriendsServiceProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
